# look at https://github.com/bmwiedemann/automation/commit/9dbabebfd779fab76e66c9c835ab28f3ebc141a9
# to fix the single proposal building and not all at once
---
story:
  default:
    desc: "Default setup"
    virtual:
      mkcloud: &default_mkcloud
        cloudsource: <%= ENV['cloudsource'] || 'develcloud6' %>
        networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>
        nodenumberlonelynode: <%= ENV['nodenumberlonelynode'] %>
        nodenumber: <%= ENV['nodenumber'] %>
        artifacts_dir: "log/"

      virsetup:
        image_size: 120G

      runners:
        - mkcloud:cleanup:
        - virsetup:configure:
        - mkcloud:prepare:
        - mkcloud:setupadmin:
        - mkcloud:installcrowbar:
            timeout: "20 minutes"
            features:
              - admin
        - mkcloud:installnodes:
        - mkcloud:installproposal:
            timeout: "25 minutes"
            features:
              - admin
              - controller
        - crowbar:batch:nova:
            features:
              - admin
              - controller
              - users
        - tempest:run:
            timeout: "20 minutes"


    qa2: &qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa2

      runners:
        - gate:prepare_admin:
        - admin_vm:prepare:
        - qa_crowbarsetup:prepareinstallcrowbar:
            timeout: "2 minutes"
        - qa_crowbarsetup:installcrowbar:
            features:
              - admin
        - qa_crowbarsetup:allocate:
            features:
              - admin
        - qa_crowbarsetup:waitcompute:
            features:
              - admin
        - tempest:run:
            timeout: "30 minutes"
            features:
              - admin
              - controller
              - users
              - images

    qa3:
      <<: *qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa3

    qa1:
      <<: *qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa1
        qa1password: qatesting
        adminip: 10.162.26.140
