---
story:
  default:
    desc: "Default cloud story"
    virtual:
      mkcloud: &default_mkcloud
        cloudsource: <%= ENV['cloudsource'] || 'develcloud6' %>
        networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>
        nodenumberlonelynode: <%= ENV['nodenumberlonelynode'] %>
        nodenumber: <%= ENV['nodenumber'] %>
        artifacts_dir: "log/"
        TESTHEAD: 1
        UPDATEREPOS: 1

      virsetup:
        image_size: 120G

      runners:
        - mkcloud:cleanup: {}
        - virsetup:configure: {}
        - mkcloud:prepare: {}
        - mkcloud:setupadmin: {}
        - mkcloud:installcrowbar:
            timeout: "20 minutes"
            features:
              - admin
        - mkcloud:instnodes: {}
        - mkcloud:proposals:
            timeout: "45 minutes"
            features:
              - admin
              - controller
        - tempest:run:
            timeout: "20 minutes"


    qa2: &qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa2

      runners:
      - gate:prepare_admin:              {}
      - admin_vm:prepare:                {}
      - qa_crowbarsetup:prepareinstallcrowbar:
          timeout: "2 minutes"
      - qa_crowbarsetup:installcrowbar:
          features:
            - admin
      - qa_crowbarsetup:reboot:          {}
      - crowbar:wait_all_discovered:     {}
      - qa_crowbarsetup:configure_nodes: {}
      - crowbar:allocate:
          features:
            - admin
      - qa_crowbarsetup:waitcompute:
          features:
            - admin
      - qa_crowbarsetup:prepare_proposals: {}
      - qa_crowbarsetup:proposal:database:
          features:
            - admin
      - qa_crowbarsetup:proposal:rabbitmq:
          features:
            - admin
      - qa_crowbarsetup:proposal:keystone:
          features:
            - admin
      - qa_crowbarsetup:proposal:swift:
          features:
            - admin
      - qa_crowbarsetup:proposal:glance:
          features:
            - admin
      - qa_crowbarsetup:proposal:cinder:
          features:
            - admin
      - qa_crowbarsetup:proposal:neutron:
          features:
            - admin
      - qa_crowbarsetup:proposal:nova:
          features:
            - admin
      - qa_crowbarsetup:proposal:nova_dashboard:
          features:
            - admin
            - controller
            - users
      - qa_crowbarsetup:proposal:heat:
          features:
            - admin
            - controller
            - users
      - qa_crowbarsetup:proposal:trove:
          features:
            - admin
            - controller
            - users
      - qa_crowbarsetup:proposal:tempest:
      - qa_crowbarsetup:testsetup:
          timeout: "30 minutes"

    qa3:
      <<: *qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa3

    qa1:
      <<: *qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa1
        qa1password: qatesting
        adminip: 10.162.26.140
