---
story:
  default:
    desc: "Default cloud story"
    virtual:
      mkcloud: &default_mkcloud
        cloudsource: <%= ENV['cloudsource'] || 'develcloud6' %>
        networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>
        nodenumberlonelynode: <%= ENV['nodenumberlonelynode'] %>
        nodenumber: <%= ENV['nodenumber'] %>
        artifacts_dir: "log/"
        TESTHEAD: <%= ENV['TESTHEAD'] || '' %>
        UPDATEREPOS: <%= ENV['UPDATEREPOS'] || '' %>
        hacloud: <%= ENV['hacloud'] %>
        clusterconfig: <%= ENV['clusterconfig'] %>

      virsetup:
        image_size: 270G

      runners:
        - mkcloud:cleanup:
        - virsetup:configure:
        - mkcloud:prepare:
        - mkcloud:setupadmin:
        - mkcloud:installcrowbar:
            timeout: "40 minutes"
            features:
              - admin
        - mkcloud:instnodes:
            timeout: "40 minutes"
        - mkcloud:proposals:
            timeout: "65 minutes"
            features:
              - admin
              - controller
        - mkcloud:testsetup:
            timeout: "60 minutes"
        - mkcloud:cct:
            timeout: "30 minutes"
        - tempest:run:
            timeout: "60 minutes"


    qa2: &qa2
      mkcloud:
        <<: *default_mkcloud
        nodenumber: 7
        want_ipmi: true
        cloud: qa2

      runners:
      - gate:prepare_admin:
      - admin_vm:prepare:
      - qa_crowbarsetup:prepareinstallcrowbar:
      - qa_crowbarsetup:addupdaterepo:
      - qa_crowbarsetup:runupdate:
      - qa_crowbarsetup:installcrowbar:
          features:
            - admin
      - qa_crowbarsetup:rebootnodes:
      - crowbar:wait_all_discovered:
      - qa_crowbarsetup:configure_nodes:
      - crowbar:allocate:
      - qa_crowbarsetup:waitcloud:
          timeout: "40 minutes"
      - qa_crowbarsetup:prepare_proposals:
      - qa_crowbarsetup:proposal:database:
          features:
            - admin
      - qa_crowbarsetup:proposal:rabbitmq:
          features:
            - admin
      - qa_crowbarsetup:proposal:keystone:
          features:
            - admin
      - qa_crowbarsetup:proposal:swift:
          features:
            - admin
      - qa_crowbarsetup:proposal:glance:
          features:
            - admin
      - qa_crowbarsetup:proposal:cinder:
          features:
            - admin
      - qa_crowbarsetup:proposal:neutron:
          features:
            - admin
      - qa_crowbarsetup:proposal:nova:
          features:
            - admin
      - qa_crowbarsetup:proposal:horizon_barclamp:
          features:
            - admin
            - controller
            - users
      - qa_crowbarsetup:proposal:ceilometer:
      - qa_crowbarsetup:proposal:heat:
      - qa_crowbarsetup:proposal:manila:
      - qa_crowbarsetup:proposal:trove:
      - qa_crowbarsetup:proposal:tempest:
      - qa_crowbarsetup:set_dashboard_alias:
      - qa_crowbarsetup:testsetup:
          timeout: "90 minutes"
      - qa_crowbarsetup:run_cct:
          timeout: "60 minutes"

    qa3:
      <<: *qa2
      mkcloud:
        <<: *default_mkcloud
        nodenumber: 8
        want_ipmi: true
        cloud: qa3

    qa1:
      <<: *qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa1
        qa1password: qatesting
        adminip: 10.162.26.140
