---
story:
  default:
    desc: "Default setup"
    virtual:
      mkcloud: &default_mkcloud
        cloudsource: <%= ENV['cloudsource'] || 'develcloud6' %>
        networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>
        artifacts_dir: "log/"

      virsetup:
        image_size: 120G

      runners:
        - mkcloud:cleanup:
            stage: "Ancient cloud build wiped out"
        - virsetup:configure:
            stage: "Setup for virtual deployment ready"
        - mkcloud:prepare:
            stage: "Environment prepared for mkcloud"
        - mkcloud:setupadmin:
            stage: "Admin node prepared for crowbar installation"
        - mkcloud:installcrowbar:
            stage: "Admin node installed"
            features:
              - admin
        - mkcloud:installnodes:
            stage: "Nodes installed"
        - mkcloud:installproposal:
            stage: "Controller node and compute node installed"
            timeout: "25 minutes"
            features:
              - admin
              - controller
        - mkcloud:testsetup:
            stage: "Tempest run"
            timeout: "20 minutes"


    qa2: &qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa2

      runners:
        - gate:prepare_admin:
            stage: "Image for admin node prepared"
        - admin_domain:prepare:
            stage: "Admin libvirt domain prepared"
        - qa_crowbarsetup:prepareinstallcrowbar:
           timeout: "2 minutes"
        - qa_crowbarsetup:installcrowbar:
           timeout: "10 minutes"
           stage: Crowbar installed
           features:
             - admin
        - qa_crowbarsetup:allocate:
           timeout: "20 minutes"
           stage: Nodes allocated
        - crowbar:batch:proposal:
           - barclamp: database
           - barclamp: nova
             timeout: "30 minutes"
             features:
               - admin
               - controller
               - users
               - images
           - barclamp: tempest
             timeout: "20 minutes"

    qa3:
      <<: *qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa3

