---
story:
  default:
    desc: "Default setup with linuxbridge as network plugin"
    qa2: &qa2
      mkcloud: &mkcloud
        cloudsource: <%= ENV['cloudsource'] || 'develcloud6' %>
        TESTHEAD: <%= ENV['TESTHEAD'] || 1 %>
        UPDATEREPOS: <%= ENV['UPDATEREPOS'] || 1 %>
        networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>

      runners: &runners
        - gate:prepare_admin:
            timeout: "5 seconds"
            stage: "Admin node prepared"
            features:
              - admin:test
              - admin:test
        - qa_crowbarsetup:test:
            timeout: "5 seconds"
            stage: "Test done"
        - qa_crowbarsetup:prepareinstallcrowbar:
            timeout: "2 minutes"
        - qa_crowbarsetup:installcrowbar:
            timeout: "10 minutes"
            stage: Crowbar installed
            features:
              - admin
        - qa_crowbarsetup:allocate:
            tiemout: "5 minutes"
            stage: Nodes allocated
      # - crowbar:batch:proposal:
      #     - database:
      #         stage: "Database proposal installed"
      #         timeout: "5 minutes"
      #     - nova:
      #         timeout: "30 minutes"
      #         stage: "Nova proposal installed"
      #         features:
      #           - admin
      #           - controller
      #     - tempest:
      #         timeout: "20 minutes"
      #         stage: "Tempest proposal installed"

    qa3:
      <<: *qa2

    virtual:
      mkcloud:
        <<: *mkcloud
        net_public: 192.168.173
        net_fixed: 192.168.174
        net_admin: 192.168.175
        adminnetmask: 255.255.248.0

      runners:
        - mkcloud:cleanup:
            stage: "Leftovers from last run cleaned up"
            timeout: "30 seconds"
       #virtsetup:detach_image:
       #virtsetup:create_image:
       #virtsetup:configure_loop_device:
       #mkcloud:prepare:
       #mkcloud:setupadmin:
       #mkcloud:installcrowbar:
       #  stage: Crowbar installed
       #  features: &admin
       #    admin:

       #mkcloud:installnodes:
       #mkcloud:installproposal:
       #  stage: Controller node installed
       #  features:
       #    <<: *admin
       #    controller:
