---
story:
  default:
    desc: "Default setup"
    virtual:
      mkcloud: &mkcloud
        cloudsource: <%= ENV['cloudsource'] || 'develcloud6' %>
        networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>
        artifacts_dir: "tmp/"

      virtsetup:
        image_size: 120G

      runners:
        - virtsetup:configure_loop_device:
            stage: "/dev/loopX set up"
            timeout: "10 seconds"
        - virtsetup:configure_image:
            stage: "Image file for deployment ready"
            timeout: "30 seconds"
        - mkcloud:prepare:
            stage: "Environment prepared for mkcloud"
            timeout: "5 minutes"
        - mkcloud:setupadmin:
            stage: "Admin node prepared for crowbar installation"
            timeout: "2 minutes"
        - mkcloud:installcrowbar:
            stage: Crowbar installed
            timeout: "15 minutes"
            features:
              - admin
        - mkcloud:installnodes:
            stage: "Nodes installed"
            timeout: "15 minutes"
        - mkcloud:installproposal:
            stage: "Controller node installed"
            timeout: "25 minutes"
            features:
              - admin
              - controller
        - mkcloud:testsetup:
            stage: "Tempest run"
            timeout: "20 minutes"


    qa2: &qa2
      mkcloud:

      runners:
        - gate:prepare_admin:
            timeout: "1 minute"
            stage: "Admin node prepared"
       #- qa_crowbarsetup:test:
       #    timeout: "5 seconds"
       #    stage: "Test done"
       #- qa_crowbarsetup:prepareinstallcrowbar:
       #    timeout: "2 minutes"
       #- qa_crowbarsetup:installcrowbar:
       #    timeout: "10 minutes"
       #    stage: Crowbar installed
       #    features:
       #      - admin
       #- qa_crowbarsetup:allocate:
       #    tiemout: "5 minutes"
       #    stage: Nodes allocated
      # - crowbar:batch:proposal:
      #     - database:
      #         stage: "Database proposal installed"
      #         timeout: "5 minutes"
      #     - nova:
      #         timeout: "30 minutes"
      #         stage: "Nova proposal installed"
      #         features:
      #           - admin
      #           - controller
      #     - tempest:
      #         timeout: "20 minutes"
      #         stage: "Tempest proposal installed"

    qa3:
      <<: *qa2

