---
story:
  default:
    desc: "Default setup"
    virtual:
      mkcloud: &default_mkcloud
        cloudsource: <%= ENV['cloudsource'] || 'develcloud6' %>
        networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>
        nodenumberlonelynode: <%= ENV['nodenumberlonelynode'] %>
        nodenumber: <%= ENV['nodenumber'] %>
        artifacts_dir: "log/"

      virsetup:
        image_size: 220G

      runners:
        - mkcloud:cleanup:
            stage: "Ancient cloud build wiped out"
        - virsetup:configure:
            stage: "Setup for virtual deployment ready"
        - mkcloud:prepare:
            stage: "Environment prepared for mkcloud"
        - mkcloud:setupadmin:
            stage: "Admin node prepared for crowbar installation"
        - mkcloud:installcrowbar:
            stage: "Admin node installed"
            timeout: "20 minutes"
            features:
              - admin
        - mkcloud:installnodes:
            stage: "Nodes installed"
        - mkcloud:installproposal:
            stage: "Controller node and compute node installed"
            timeout: "25 minutes"
            features:
              - admin
              - controller
        - crowbar:batch:nova:
            features:
              - admin
              - controller
              - users
        - tempest:run:
            stage: "Tempest run"
            timeout: "20 minutes"


    qa2: &qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa2

      runners:
        - gate:prepare_admin:
            stage: "Image for admin node prepared"
        - admin_domain:prepare:
            stage: "Admin libvirt domain prepared"
        - qa_crowbarsetup:prepareinstallcrowbar:
            timeout: "2 minutes"
            stage: "Crowbar installation prepared"
        - qa_crowbarsetup:installcrowbar:
            stage: "Crowbar installed"
            features:
              - admin
        - qa_crowbarsetup:allocate:
            stage: "Nodes allocated"
        - qa_crowbarsetup:waitcompute:
            stage: "Nodes ready for barclamp deployment"
        - qa_crowbarsetup:proposal:
            stage: "Proposals installed"

    qa3:
      <<: *qa2
      mkcloud:
        <<: *default_mkcloud
        cloud: qa3

