git:
  automation:
    url: github.com:suse-cloud/automation
    branch: master

stories:
  - default.yml
# - ceph.yml

targets:
  qa2:
    gate:
      fqdn: gate.cloud2adm.qa.suse.de
      user: root
      password:
      admin_domain: crowbar2
    admin_node:
      ip: 10.162.24.10
      fqdn: crowbar.cloud2adm.qa.suse.de
      user: root
      password:

  qa3:
    gate:
      fqdn: gate.cloud3adm.qa.suse.de
      user: root
      password:
      admin_domain: crowbar3
    admin_node:
      ip: 10.162.24.10
      fqdn: crowbar.cloud3adm.qa.suse.de
      user: root
      password:

  virtual:
    admin_node:
      ip: 192.168.175.10
      user: root
      password:
