git:
  automation:
    url: github.com:suse-cloud/automation
    branch: master

targets:
  qa2:
    desc: "Cloud 2 in rack 19 in server room 2"
    gate:
      fqdn: gate.cloud2adm.qa.suse.de
      user: root
      admin_domain: crowbar2
    admin_node:
      ip: 10.162.24.10
      fqdn: crowbar.cloud2adm.qa.suse.de
      user: root
      password: linux

  qa3:
    desc: "Cloud 3 in rack 19 in server room 2"
    gate:
      fqdn: gate.cloud3adm.qa.suse.de
      user: root
      admin_domain: crowbar3
    admin_node:
      ip: 10.162.24.10
      fqdn: crowbar.cloud3adm.qa.suse.de
      user: root
      password:

  virtual:
    desc: "Virtualized environment using libvirt"
    gate:
      fqdn: manacor.suse.cz
      user: vmoravec
      port: 22
    admin_node:
      ip: CAN'T BE BLANK
      user: root
      password:


timeout:
  ssh: 5
