git:
  automation:
    url: github.com:suse-cloud/automation
    branch: master

targets:
  # SSH key based authentication
  qa2:
    desc: "Cloud 2 in rack 19 in server room 2 in Nürnberg"
    gate:
      fqdn: gate.cloud2adm.qa.suse.de
      user: root
      admin_domain:
        name: crowbar2
        user: root
    admin_node:
      ip: 10.162.24.10
      fqdn: crowbar.cloud2adm.qa.suse.de
      ssh: &ssh
        user: root
        password: linux
      api: &api
        user: crowbar
        password: crowbar

  # SSH key based authentication
  qa3:
    desc: "Cloud 3 in rack 19 in server room 2 in Nürnberg"
    gate:
      fqdn: gate.cloud3adm.qa.suse.de
      user: root
      admin_domain:
        name: crowbar3
        user: root
    admin_node:
      ip: 10.162.25.10
      fqdn: crowbar.cloud3adm.qa.suse.de
      ssh:
        <<: *ssh
      api:
        <<: *api

  virtual:
    desc: "Virtualized environment libvirt"
    gate:
      fqdn: localhost

    admin_node:
      ip: 192.168.175.10
      ssh:
        <<: *ssh
      api:
        <<: *api
cucumber:
  formats:
    - pretty: "log/features"
    - json: "log/features"

timeout:
  ssh: 5
