targets:
  # SSH key based authentication
  qa1:
    desc: "Cloud 1 (location unknown)"
    gate:
      fqdn: gate.cloudadm.qa.suse.de
      user: root
      admin_vm:
        domain: crowbar
        name: crowbar2
        user: root
    admin_node: &admin_node
    admin_node:
      ip: 10.162.26.140
      fqdn: crowbar.cloud2adm.qa.suse.de
      ssh:
        user: root
        password: linux
      api:
        user: crowbar
        password: crowbar
    control_node: &control_node
      ssh:
        user: root
        password: linux
        port: 22

  # SSH key based authentication
  qa2:
    desc: "Cloud 2 in rack 19 in server room 2 in Nürnberg"
    gate:
      fqdn: gate.cloud2adm.qa.suse.de
      user: root
      admin_vm:
        name: crowbar2
        user: root
    admin_node:
      <<: *admin_node
      ip: 10.162.24.10
      fqdn: crowbar.cloud2adm.qa.suse.de
    control_node:
      <<: *control_node

  # SSH key based authentication
  qa3:
    desc: "Cloud 3 in rack 19 in server room 2 in Nürnberg"
    gate:
      fqdn: gate.cloud3adm.qa.suse.de
      user: root
      admin_vm:
        name: crowbar3
        user: root
    admin_node:
      <<: *admin_node
      ip: 10.162.25.10
      fqdn: crowbar.cloud3adm.qa.suse.de
    control_node:
      <<: *control_node
  # Libvirt, lvm and friends
  virtual:
    desc: "Virtualized environment with libvirt"
    gate:
      fqdn: localhost
    admin_node:
      <<: *admin_node
      ip: CAN'T BE BLANK
    control_node:
      <<: *control_node

