story:
  ha_detail:
    desc: "HA detailed cloud story"
    virtual:
      mkcloud: &ha_mkcloud
        cloudsource: <%= ENV['cloudsource'] || 'develcloud6' %>
        networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>
        nodenumberlonelynode: <%= ENV['nodenumberlonelynode'] %>
        nodenumber: <%= ENV['nodenumber'] || 8 %>
        artifacts_dir: "log/"
        TESTHEAD: <%= ENV['TESTHEAD'] || '' %>
        UPDATEREPOS: <%= ENV['UPDATEREPOS'] || '' %>
        hacloud: 1
        clusterconfig: services+data=2:network=3

      virsetup:
        image_size: 370G

      runners:
        - mkcloud:cleanup:
        - virsetup:configure:
        - mkcloud:prepare:
        - mkcloud:setupadmin:
        - mkcloud:installcrowbar:
            timeout: "40 minutes"
            features:
              - admin
        - mkcloud:instnodes:
            timeout: "40 minutes"
        - mkcloud:proposals:
            timeout: "65 minutes"
            features:
              - admin
              - controller
        - mkcloud:testsetup:
            timeout: "60 minutes"
        - mkcloud:cct:
            timeout: "30 minutes"
        - tempest:run:
            timeout: "60 minutes"


    qa3: &qa3
      mkcloud:
        <<: *ha_mkcloud
        nodenumber: 8
        want_ipmi: true
        cloud: qa3

      runners:
      - gate:prepare_admin:
      - admin_vm:prepare:
      - qa_crowbarsetup:prepareinstallcrowbar:
      - qa_crowbarsetup:installcrowbar:
      - qa_crowbarsetup:allocate:
      - qa_crowbarsetup:waitcloud:
          timeout: "40 minutes"
      - qa_crowbarsetup:prepare_proposals:
      - qa_crowbarsetup:cluster_node_assignment:
      - qa_crowbarsetup:proposal:pacemaker:
      - qa_crowbarsetup:proposal:database:
      - qa_crowbarsetup:proposal:rabbitmq:
      - qa_crowbarsetup:proposal:keystone:
      - qa_crowbarsetup:proposal:swift:
      - qa_crowbarsetup:proposal:glance:
      - qa_crowbarsetup:proposal:cinder:
      - qa_crowbarsetup:proposal:neutron:
      - qa_crowbarsetup:proposal:nova:
      - qa_crowbarsetup:proposal:horizon:
          features:
            - admin
            - controller
            - users
      - qa_crowbarsetup:proposal:ceilometer:
      - qa_crowbarsetup:proposal:heat:
      - qa_crowbarsetup:proposal:manila:
      - qa_crowbarsetup:proposal:trove:
      - qa_crowbarsetup:proposal:tempest:
