---
story:
  default:
    qa2: &qa2
      desc: Default setup for qa2 cloud with linuxbridge as network plugin
      ignore_features: <%= ENV['ignore_features'] || false %>
      nodes:
        - host: d00-25-90-e5-04-54
          alias: dashboard
          role: controller

      mkcloud: &mkcloud
        cloudsource: <%= ENV['cloudsource'] || 'develcloud6' %>
        TESTHEAD: <%= ENV['TESTHEAD'] || 1 %>
        UPDATEREPOS: <%= ENV['UPDATEREPOS'] || 1 %>
        networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>

      cct:
        admin_node: &admin_node
          ssh:
            user: root
            password: linux
          api:
            user: crowbar
            password: crowbar

      # default timeout will be 5 or 10 minutes
      runners: &runners
        - config_gate:prepare_admin_node
        - qa_crowbarsetup:prepareinstallcrowbar:
            timeout: 2 minutes
        - qa_crowbarsetup:installcrowbar:
            timeout: "10 minutes"
            stage: Crowbar installed
            features:
              - admin

        qa_crowbarsetup:allocate:
          stage: Nodes allocated
        qa_crowbarsetup:waitcompute:
        crowbar:batch:proposal:
          - database:
              stage: "Database barclamp installed"
              timeout: 5 minutes
          - nova:
              timeout: "30 minutes"
              stage: Controller node installed
              features:
                - admin
                - controller

          - tempest:
              timeout: 20 minutes
              stage: Tempest proposal installed
              features:
                - tempest

    qa3:
      <<: *qa2
      desc: Default setup for qa3 cloud with linuxbridge as network plugin

      cct:
        admin_node:
          <<: *admin_node


    virtual:
      <<: *qa2
      desc: Default setup for virtual cloud with linuxbridge as network plugin
      mkcloud:
        <<: *mkcloud
        net_public: 192.168.173
        net_fixed: 192.168.174
        net_admin: 192.168.175
        adminnetmask: 255.255.248.0
        nodenumber: <%= ENV['nodenumber'] || 3 %>
        networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>
        compute_node_memory: <%= ENV['compute_node_memory'] || 4194304 %>
        lvm_size: <%= ENV['lvm_size'] || '160G' %>
        computenode_hdd_size: <%= ENV['computenode_hdd_size'] || '20G' %>
        controller_hdd_size: <%= ENV['controller_hdd_size'] || '40G' %>

      cct:
        admin_node:
          <<: *admin_node
          ip: 192.168.175.10

      runners:
        mkcloud:cleanup:
        virtsetup:detach_image:
        virtsetup:create_image:
        virtsetup:configure_loop_device:
        mkcloud:prepare:
        mkcloud:setupadmin:
        mkcloud:installcrowbar:
          stage: Crowbar installed
          features: &admin
            admin:

        mkcloud:installnodes:
        mkcloud:installproposal:
          stage: Controller node installed
          features:
            <<: *admin
            controller:
