---
story:
  default: &default
    desc: Default setup for virtual deployment with linuxbridge as network plugin
    ignore_features: <%= ENV['ignore_features'] || false %>
    mkcloud: &mkcloud
      cloudsource: <%= ENV['cloudsource'] || 'develcloud5' %>
      net_public: 192.168.173
      net_fixed: 192.168.174
      net_admin: 192.168.175
      adminnetmask: 255.255.248.0
      TESTHEAD: <%= ENV['TESTHEAD'] || 1 %>
      UPDATEREPOS: <%= ENV['UPDATEREPOS'] || 1 %>
      nodenumber: <%= ENV['nodenumber'] || 3 %>
      networkingplugin: <%= ENV['networkingplugin'] || 'linuxbridge' %>
      compute_node_memory: <%= ENV['compute_node_memory'] || 4194304 %>
      lvm_size: <%= ENV['lvm_size'] || '160G' %>
      computenode_hdd_size: <%= ENV['computenode_hdd_size'] || '20G' %>
      controller_hdd_size: <%= ENV['controller_hdd_size'] || '40G' %>


    cct:
      admin_node:
        ip: 192.168.175.10
        ssh:
          user: root
          password: linux

        api:
          user: crowbar
          password: crowbar

    runners: &runners
      mkcloud:cleanup:
      mkcloud:prepare:
        stage: Init
      mkcloud:setupadmin:
        stage:
      mkcloud:installcrowbar:
        stage: Crowbar installed
        features: &admin
          admin:

      mkcloud:installnodes:
      mkcloud:installproposal:
        stage: Controller node installed
        features:
          <<: *admin
          controller:

  default:openswitch:
    <<: *default
    desc: Default setup for virtual deployment with openswitch as network plugin
    mkcloud:
      <<: *mkcloud
      networkingplugin: openswitch

